import Head from 'next/head';
import {
  AiFillFacebook,
  AiFillLinkedin,
  AiFillInstagram,
} from 'react-icons/ai';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { useState } from 'react';
import deved from '../public/dev-ed-wave.png';
import code from '../public/code.png';
import design from '../public/design.png';
import consulting from '../public/consulting.png';
import Image from 'next/image';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import Link from 'next/link';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Portofolio Bagas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40 font-sans">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyme</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl font-mono">
              Bagas Prasetyo
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl font-mono">
              Front End Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Fresh Graduate yang memfokuskan dirinya belajar dan mengasah skill
              front end. Ini portofolio ku, enjoy it!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <Link href="https://www.facebook.com/bagas.prasetyo2/">
                <a target="_blank">
                  <AiFillFacebook />
                </a>
              </Link>
              <Link href="https://www.linkedin.com/in/bagas-p-88226a129/">
                <a target="_blank">
                  <AiFillLinkedin />
                </a>
              </Link>
              <Link href="https://www.instagram.com/bgaspra11/">
                <a target="_blank">
                  <AiFillInstagram />
                </a>
              </Link>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-4xl py-1 dark:text-white font-mono">
              Skill Ku
            </h3>
            <p className="text-xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              Awalnya saya merupakan fullstack developer dan mengerjakan
              beberapa project dari
              <span className="text-teal-500"> pemerintahan </span>
              khususnya saat saya masih seorang{' '}
              <span className="text-teal-500">mahasiswa </span>
              tapi saat ini saya lebih memfokuskan diri pada bidang front end
              developer.
            </p>
            <p className="text-xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              Ini adalah skill yang ku kuasai di bidang programming.
            </p>
          </div>
          <div className="lg:flex gap-10 text-xl">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-2xl font-medium pt-8 pb-2 font-mono">
                Slicing Design
              </h3>
              <p className="py-2">
                Slicing Design dari figma dan menerjemahkannya ke ccs murni
                ataupun library css yang ada saat ini.
              </p>
              <h4 className="py-4 text-teal-600">Yang ku kuasai</h4>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">Boostrap</p>
              <p className="text-gray-800 py-1">Tailwind</p>
              <p className="text-gray-800 py-1">Material UI</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-2xl font-medium pt-8 pb-2 font-mono">
                Coding Front End
              </h3>
              <p className="py-2">
                Saat ini saya memfokuskan front end developer, saya fokus ke
                bahasa javascript
              </p>
              <h4 className="py-4 text-teal-600">Yang Ku kuasai</h4>
              <p className="text-gray-800 py-1">React Js</p>
              <p className="text-gray-800 py-1">Next Js</p>
              <p className="text-gray-800 py-1">Restful API</p>
              <p className="text-gray-800 py-1">Bekerja dengan Git & Github</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-2xl font-medium pt-8 pb-2 font-mono">
                Back End Developer
              </h3>
              <p className="py-2">
                Saya mengetahui dan bisa mengerjakan back end tapi tidak
                mendalam, karena saya dulu mempelajarinya. Bahasa Pemrograman
                yang saya pakai yaitu PHP walaupun sudah lama saya tidak
                menyentuhnya lagi.
              </p>
              <h4 className="py-4 text-teal-600">Yang Ku kuasai</h4>
              <p className="text-gray-800 py-1">PHP</p>
              <p className="text-gray-800 py-1">Laravel</p>
              <p className="text-gray-800 py-1">MySql</p>
              <p className="text-gray-800 py-1">Mongo</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white font-mono">
              Portofolio
            </h3>
            <p className="text-xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              Pertama kali mengerjakan project saat kuliah dan itu project
              lembaga <span className="text-teal-500"> pemerintahan </span> dan
              tidak bisa di akses publik dan juga ada yang sudah tidak aktif
              lagi. Di bawah ini adalah project yang saya kerjakan setelah saya
              berfokus menjadi
              <span className="text-teal-500"> front end developer. </span>
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
